/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package fr.rss.download.api.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import fr.rss.download.api.exceptions.ApiException;
import fr.rss.download.api.model.AlldebridRemoteFile;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@Api(value = "allDebrid")
public interface IAllDebridApiController {

	@ApiOperation(value = "Recupere un lien débridé depuis allDebrid", response = AlldebridRemoteFile.class, tags = { "allDebrid" })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Debridage ok", response = AlldebridRemoteFile.class),
			@ApiResponse(code = 500, message = "Erreur lors du traitement", response = ApiException.class) })

	@RequestMapping(value = "/allDebrid", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<?> allDebridDownload(@ApiParam(value = "Lien à débrider", required = true) @RequestParam("link") String link) throws ApiException;

}
